// Generated by FlutterFire CLI — do not edit manually.
// To regenerate run: flutterfire configure --project=feddan-mobile

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web platform is not supported.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrmYEw0qtvou1oIt2rVedgLQZ6CgsyGeo',
    appId: '1:991040162518:android:21ff8e03029657b37a5777',
    messagingSenderId: '991040162518',
    projectId: 'feddan-mobile',
    storageBucket: 'feddan-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpiS0A1pfedIOkz-HQ5JJmBM1IxYvEnIo',
    appId: '1:991040162518:ios:a3173f77b559478a7a5777',
    messagingSenderId: '991040162518',
    projectId: 'feddan-mobile',
    storageBucket: 'feddan-mobile.firebasestorage.app',
    iosBundleId: 'com.feddan.feddan',
  );

}